import { CardImage, CardLogo1, CardLogo2 } from "@/assets/images";

export const cardsData = [
    {
        brand_logo1: CardLogo1,
        brand_logo2: CardLogo2,
        image: CardImage,
        title: "Economy",
        locals: ["Tash", "Dubai", "Mad"],
        date_start: "9 Nov 12:00",
        date_end: "24 Nov 12:00",
        deadline: 5,
        price: 1298,
    },
    {
        brand_logo1: CardLogo1,
        brand_logo2: CardLogo2,
        image: CardImage,
        title: "Economy",
        locals: ["Tash", "Dubai", "Mad"],
        date_start: "9 Nov 12:00",
        date_end: "24 Nov 12:00",
        deadline: 5,
        price: 1298,
    },
    {
        brand_logo1: CardLogo1,
        brand_logo2: CardLogo2,
        image: CardImage,
        title: "Economy",
        locals: ["Tash", "Dubai", "Mad"],
        date_start: "9 Nov 12:00",
        date_end: "24 Nov 12:00",
        deadline: 5,
        price: 1298,
    },
    {
        brand_logo1: CardLogo1,
        brand_logo2: CardLogo2,
        image: CardImage,
        title: "Economy",
        locals: ["Tash", "Dubai", "Mad"],
        date_start: "9 Nov 12:00",
        date_end: "24 Nov 12:00",
        deadline: 5,
        price: 1298,
    },
    {
        brand_logo1: CardLogo1,
        brand_logo2: CardLogo2,
        image: CardImage,
        title: "Economy",
        locals: ["Tash", "Dubai", "Mad"],
        date_start: "9 Nov 12:00",
        date_end: "24 Nov 12:00",
        deadline: 5,
        price: 1298,
    },
    {
        brand_logo1: CardLogo1,
        brand_logo2: CardLogo2,
        image: CardImage,
        title: "Economy",
        locals: ["Tash", "Dubai", "Mad"],
        date_start: "9 Nov 12:00",
        date_end: "24 Nov 12:00",
        deadline: 5,
        price: 1298,
    },
]