import "@/styles/globals.css";
import "@/styles/global.scss";
import IntlWrapperProvider from "@/utils/intlWrapperProvider";
import type { AppProps } from "next/app";
import Head from "next/head";
import Layout from "@/components/Layout";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const queryClient = new QueryClient();

export default function App({ Component, pageProps }: AppProps) {
  const { siteSettings, ...restProps } = pageProps;
  return (
    <QueryClientProvider client={queryClient}>
      <IntlWrapperProvider>
        <Layout siteSettings={siteSettings}>
          <Head>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...restProps} />
        </Layout>
      </IntlWrapperProvider>
    </QueryClientProvider>
  );
}